//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniCloud.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public string FileName { get; set; }
        public string ContentType { get; set; }
        public string FileSizeInByte { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int FileOwnerId { get; set; }
        public string Uri { get; set; }
        public int Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
